name: Agent

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/agent.yml
      - packages/agent-*/**/*
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - agent: agent-trust-wallet
            repo: trustwallet/assets
            ref: master
          - agent: agent-ethereum-optimism
            repo: ethereum-optimism/ethereum-optimism.github.io
            ref: master
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - uses: actions/checkout@v6
        with:
          # PLEASE be aware that this is a security risk when you allow untrusted repositories to be checked out.
          # While the agent is executed such that we're only reading files which pose no security risk,
          # it's nonetheless possible through other means to execute arbitrary code
          # when you attempt to do "TOO MUCH" outside its intended use case.
          path: packages/${{ matrix.agent }}/.repo
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}

      - run: turbo run agent
        working-directory: packages/${{ matrix.agent }}

      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          title: "chore(agent): ${{ matrix.agent }}"
          commit-message: "chore(agent): ${{ matrix.agent }}"
          branch: agents/${{ matrix.agent }}
          draft: always-true
